name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-lipo
      run: cargo install cargo-lipo
    - name: Build
      run: cargo lipo
